services:
  app:
    image: naooff/personal-finance-tracker-api:latest
    container_name: personal-finance-tracker-api-container
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: jpa
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MVC_CONVERTERS_PREFERRED_JSON_MAPPER: jackson
      SPRING_MVC_CONTENTNEGOTIATION_FAVOR_PARAMETER: false
      SPRING_MVC_CONTENTNEGOTIATION_MEDIA_TYPES_JSON: application/json
      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: ${REDIS_URL}
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_DATABASE: ${REDIS_DB}
    depends_on:
      - db
      - cache

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: personal_finance_app_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache_db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    driver: local
  redis-data: