name: Project CI/CD Flow

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 21 using Temurin and enable Maven caching
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Optional: Submit Maven's dependency graph to GitHub to improve Dependabot alerts
      - name: Update Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Build and push the project using Docker only on the 'main' branch
      - name: Build & push Docker image
        if: github.ref == 'refs/heads/main'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: naooff/personal-finance-tracker-api
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
