# This workflow builds a Java project with Maven and caches/restores dependencies
# to improve workflow execution time.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Note: This workflow uses actions provided by third parties, which are not certified by GitHub.
# They are governed by separate terms of service, privacy policies, and support documentation.

name: Project CI/CD Flow

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up JDK 21 using Temurin and enable Maven caching
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Optional: Submit Maven's dependency graph to GitHub to improve Dependabot alerts
    - name: Update Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
